<?php

function cobalt_init() {
  if (user_access('use cobalt')) {
    global $user;
    
    if (variable_get('cobalt_gears_init',1)) {
      drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/gears_init.js');
    }
    
    if (variable_get('cobalt_jquery_json',1)) {
      drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/jquery.json-1.3.min.js');
    }
    
    if (variable_get('cobalt_jquery_hotkeys',1)) {
      drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/jquery.hotkeys.js');
    }
    
    drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/minimal-gears-wrapper.js');
    
    drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/cobalt.js');
    drupal_add_js(drupal_get_path('module', 'cobalt') . '/js/cobalt.menu.js');
    drupal_add_js(array('cobalt'=>array('state'=>$user->uid, 'path' => $_GET['q'])), 'setting');
    
    drupal_add_css(drupal_get_path('module', 'cobalt') . '/css/cobalt.css');
  }
}

function cobalt_perm() {
  return array('use cobalt');
}

function cobalt_menu() {
  $items = array();
  $items['cobalt/alias'] = array(
    'title' => t('Forward to the correct alias'),
    'page callback' => 'cobalt_forward_to_alias',
    'access arguments' => array('use cobalt'),
    'type' => MENU_CALLBACK,
  );
  $items['cobalt/data/menu_json'] = array(
    'title' => t('Serialized menu'),
    'page callback' => 'cobalt_menu_json',
    'access arguments' => array('use cobalt'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/cobalt'] = array(
    'title' => t('Cobalt configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cobalt_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'cobalt_admin.inc.php',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
  );
  $items['cobalt/update'] = array(
    'title' => t('Cobalt update'),
    'page callback' => 'cobalt_js_update',
    'page arguments' => array('cobalt_settings'),
    'access arguments' => array('use cobalt'),
    'file' => 'cobalt_update.inc.php',
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );
  return $items;
}

function cobalt_forward_to_alias() {
  $url_parts = array();
  $i = 2;
  while (arg($i)) {
    $url_parts[] = arg($i);
    $i++;
  }
  $path = join('/',$url_parts);
  drupal_goto($path);
}

function cobalt_menu_json() {
   $menu_names = menu_get_names();
   
   $tree = array();
   foreach ($menu_names as $name) {
    $tree += menu_tree_all_data($name);
   }
   
   $data = array();
   _cobalt_menu_data_recursive($tree, $data);
   
   drupal_alter('cobalt_menu', $data);
   
   print drupal_to_js($data);
   exit;
}

function _cobalt_menu_data_recursive($tree, &$data) {
  foreach($tree as $key => $item) {
    $link = $item['link'];
    if (!$link['hidden'] && $link['access']) {
      $data[$link['mlid']] = array($link['href'], $link['title']);
      if ($item['below']) {
        _cobalt_menu_data_recursive($item['below'], $data);
      }
    }
  }
}