<?php

function quicksilver_init() {
  if (user_access('use quicksilver')) {
    global $user;
    
    if (variable_get('quicksilver_gears_init',1)) {
      drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/gears_init.js');
    }
    
    if (variable_get('quicksilver_jquery_json',1)) {
      drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/jquery.json-1.3.min.js');
    }
    
    if (variable_get('quicksilver_jquery_hotkeys',1)) {
      drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/jquery.hotkeys.js');
    }
    
    drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/minimal-gears-wrapper.js');
    
    drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/qs.js');
    drupal_add_js(drupal_get_path('module', 'quicksilver') . '/js/qs.menu-catalog.js');
    drupal_add_js(array('quicksilver'=>array('state'=>$user->uid)), 'setting');
    
    drupal_add_css(drupal_get_path('module', 'quicksilver') . '/css/qs.css');
  }
}

function quicksilver_perm() {
  return array('use quicksilver');
}

function quicksilver_menu() {
  $items = array();
  $items['quicksilver/data/menu_json'] = array(
    'title' => t('Serialized menu'),
    'page callback' => 'quicksilver_menu_json',
    'access arguments' => array('use quicksilver'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/quicksilver'] = array(
    'title' => t('Quicksilver configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quicksilver_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'quicksilver_admin.inc.php',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
  );
  return $items;
}

function quicksilver_menu_json() {
   $menu_names = menu_get_names();
   
   $tree = array();
   foreach ($menu_names as $name) {
    $tree += menu_tree_all_data($name);
   }
   
   $data = array();
   _quicksilver_menu_data_recursive($tree, $data);
   
   drupal_alter('quicksilver_menu', $data);
   
   print drupal_to_js($data);
   exit;
}

function _quicksilver_menu_data_recursive($tree, &$data) {
  foreach($tree as $key => $item) {
    $link = $item['link'];
    if (!$link['hidden'] && $link['access']) {
      $data[$link['mlid']] = array($link['href'], $link['title']);
      if ($item['below']) {
        _quicksilver_menu_data_recursive($item['below'], $data);
      }
    }
  }
}